CREATE TABLE employee (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    AGE INT,
    BIRTH_DATE DATE,
    ADDRESS VARCHAR(250),
    ACTIVEE BOOLEAN
);